import { VerticalConfig } from "./types";

export const VERTICALS: Record<string, VerticalConfig> = {
  ecommerce: {
    id: "ecommerce",
    name: "E-commerce & Retail",
    shortName: "E-comm",
    newsKeywords: [
      "product photography ecommerce",
      "visual content catalog expansion",
      "DTC brand launch",
      "ecommerce rebrand visual",
      "hired Chief Creative Officer",
    ],
    jobTitles: [
      "Creative Director ecommerce",
      "Ecommerce Photographer",
      "Visual Content Manager",
      "Content Producer brand",
    ],
    govKeywords: ["photography services", "creative services"],
    scoringKeywords: [
      "product photography",
      "visual content",
      "catalog",
      "DTC",
      "rebrand",
      "creative director",
      "ecommerce",
      "retail",
    ],
  },
  realestate: {
    id: "realestate",
    name: "Real Estate & PropTech",
    shortName: "Real Estate",
    newsKeywords: [
      "real estate photography listing",
      "proptech expansion funding",
      "real estate platform launch",
      "iBuyer listing volume",
      "listing media technology",
    ],
    jobTitles: [
      "Real Estate Photographer",
      "Visual Content Manager real estate",
      "Head of Creative proptech",
      "Photography Operations Manager",
    ],
    govKeywords: ["photo documentation", "media production real estate"],
    scoringKeywords: [
      "real estate photography",
      "listing",
      "proptech",
      "iBuyer",
      "property",
      "real estate platform",
      "brokerage",
    ],
  },
  hospitality: {
    id: "hospitality",
    name: "Hospitality & Travel",
    shortName: "Hospitality",
    newsKeywords: [
      "hotel photography visual content",
      "hotel opening new property",
      "travel brand refresh visual",
      "OTA content partnership",
      "hospitality visual marketing",
    ],
    jobTitles: [
      "Brand Photographer hospitality",
      "Creative Director hotel",
      "Content Producer travel",
      "Visual Content Manager hospitality",
    ],
    govKeywords: ["photography services tourism", "media production hospitality"],
    scoringKeywords: [
      "hotel photography",
      "hospitality",
      "travel brand",
      "OTA",
      "hotel opening",
      "property management",
      "resort",
    ],
  },
  foodbev: {
    id: "foodbev",
    name: "Food & Beverage",
    shortName: "Food & Bev",
    newsKeywords: [
      "food photography CPG launch",
      "DTC food brand funding",
      "restaurant chain expansion",
      "beverage rebrand visual",
      "food brand Series A",
    ],
    jobTitles: [
      "Food Photographer",
      "Creative Director CPG",
      "Content Producer food beverage",
      "Brand Photographer restaurant",
    ],
    govKeywords: ["photography services food", "media production"],
    scoringKeywords: [
      "food photography",
      "CPG",
      "DTC food",
      "restaurant",
      "beverage",
      "menu",
      "culinary",
      "food brand",
    ],
  },
  marketplace: {
    id: "marketplace",
    name: "Marketplace & Platform",
    shortName: "Marketplace",
    newsKeywords: [
      "creator economy platform content",
      "content at scale marketplace",
      "marketplace visual standards",
      "gig platform expansion",
      "UGC strategy professional content",
    ],
    jobTitles: [
      "Head of Creative marketplace",
      "Visual Content Manager platform",
      "Content Producer marketplace",
      "Photography Operations Manager",
    ],
    govKeywords: ["creative services digital", "visual content services"],
    scoringKeywords: [
      "creator economy",
      "marketplace",
      "content at scale",
      "gig platform",
      "UGC",
      "visual standards",
      "platform",
    ],
  },
  finserv: {
    id: "finserv",
    name: "Financial Services",
    shortName: "FinServ",
    newsKeywords: [
      "fintech rebrand visual",
      "IPO visual assets brand",
      "brand refresh Series B fintech",
      "wealth management platform launch",
      "financial services marketing rebrand",
    ],
    jobTitles: [
      "Creative Director fintech",
      "Head of Creative financial",
      "Brand Photographer corporate",
      "Content Producer financial services",
    ],
    govKeywords: ["photography services financial", "media production"],
    scoringKeywords: [
      "fintech",
      "rebrand",
      "IPO",
      "wealth management",
      "Series B",
      "financial services",
      "brand refresh",
    ],
  },
};

export const VERTICAL_ORDER = [
  "ecommerce",
  "realestate",
  "hospitality",
  "foodbev",
  "marketplace",
  "finserv",
] as const;
